pom: include slf4j-api and slf4j-simple as deps
Without slf4j-api:
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at hdf.object.Datatype.<clinit>(Unknown Source)
	at neurord.numeric.grid.ResultWriterHDF5.<clinit>(ResultWriterHDF5.java:60)
	at neurord.model.SDRun.loadFromFile(SDRun.java:470)
	at neurord.StochDiff.main(StochDiff.java:168)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 4 more

Without slf4j-simple there's another warning:
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

I also tried slf4j-log4j12, but that results in hundreds of strange warnings:
log4j:WARN No appenders could be found for logger (hdf.object.FileFormat).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
HDF5-DIAG: Error detected in HDF5 (1.8.18) thread 0:
  #000: ../../src/H5A.c line 476 in H5Aopen_by_name(): can't open attribute
    major: Attribute
    minor: Can't open object
  #001: ../../src/H5Aint.c line 456 in H5A_open_by_name(): unable to load attribute info from object header
    major: Attribute
    minor: Unable to initialize object
  #002: ../../src/H5Oattribute.c line 537 in H5O_attr_open_by_name(): can't locate attribute: 'PALETTE'
    major: Attribute
    minor: Object not found
HDF5-DIAG: Error detected in HDF5 (1.8.18) thread 0:
  #000: ../../src/H5A.c line 476 in H5Aopen_by_name(): can't open attribute
    major: Attribute
    minor: Can't open object
  #001: ../../src/H5Aint.c line 456 in H5A_open_by_name(): unable to load attribute info from object header
    major: Attribute
    minor: Unable to initialize object
  #002: ../../src/H5Oattribute.c line 537 in H5O_attr_open_by_name(): can't locate attribute: 'PALETTE'
    major: Attribute
    minor: Object not found
...

So let's stick to slf4j-api + slf4j-simple, it seems to work nicely.