ResultWriterHDF5: fix writing of empty arrays
Apparently chunking does not work for size 0 arrays. For example, the
list of neighbours with a single-voxel model is [1×0], which caused
the following tb:
13:54:03.018 E n.SDCalc - Trial 0 failed!
 java.lang.RuntimeException: ncsa.hdf.hdf5lib.exceptions.HDF5FunctionArgumentException: Out of range
        at neurord.numeric.grid.ResultWriterHDF5.writeGrid(ResultWriterHDF5.java:248) ~[classes/:?]
        at neurord.numeric.grid.GridCalc._run(GridCalc.java:92) ~[classes/:?]
        at neurord.numeric.BaseCalc.run(BaseCalc.java:123) ~[classes/:?]
        at neurord.SDCalc.run(SDCalc.java:87) [classes/:?]
        at neurord.StochDiff.main(StochDiff.java:184) [classes/:?]
Caused by: ncsa.hdf.hdf5lib.exceptions.HDF5FunctionArgumentException: Out of range
        at ncsa.hdf.hdf5lib.H5.H5Pset_chunk(Native Method) ~[hdf-java-2.8.jar:?]
        at ncsa.hdf.hdf5lib.H5.H5Pset_chunk(H5.java:5248) ~[hdf-java-2.8.jar:?]
        at ncsa.hdf.object.h5.H5ScalarDS.create(H5ScalarDS.java:1531) ~[hdf-java-2.8.jar:?]
        at ncsa.hdf.object.h5.H5File.createScalarDS(H5File.java:1302) ~[hdf-java-2.8.jar:?]
        at ncsa.hdf.object.FileFormat.createScalarDS(FileFormat.java:1154) ~[hdf-java-2.8.jar:?]
        at neurord.numeric.grid.ResultWriterHDF5.writeArray(ResultWriterHDF5.java:1200) ~[classes/:?]
        at neurord.numeric.grid.ResultWriterHDF5$Trial._writeGrid(ResultWriterHDF5.java:497) ~[classes/:?]
        at neurord.numeric.grid.ResultWriterHDF5._writeGrid(ResultWriterHDF5.java:264) ~[classes/:?]
        at neurord.numeric.grid.ResultWriterHDF5.writeGrid(ResultWriterHDF5.java:246) ~[classes/:?]
        ... 4 more

Work around by disabling chunking and compression when size is 0.