NextReactionQueue: fix calculation of reverse reaction if forwardRate is 0
The code assumed that forwardRate is always >0, and that if the reaction is being created
from the reverseRate, previous reaction must have been the "forward" one.

11:07:18.067 E n.n.BaseCalc - neurord.numeric.grid.AdaptiveGridCalc@4d49af10: failed (seed=123)
11:07:18.067 E n.SDCalc - Trial 0 failed!
 java.lang.RuntimeException: Reaction el.0 AChm1RGq→ACh+m1RGq added to Reaction el.0 m1RGq→Gqabg+m1R as reverse but Reaction el.0 Gqabg+m1R→m1RGq was added before
        at neurord.numeric.grid.NextEventQueue$NextEvent.addReverse(NextEventQueue.java:412) ~[neurord-3.1.4-all-deps.jar:?]
        at neurord.numeric.grid.NextEventQueue.createReactions(NextEventQueue.java:1835) ~[neurord-3.1.4-all-deps.jar:?]
        at neurord.numeric.grid.NextEventQueue.create(NextEventQueue.java:1934) ~[neurord-3.1.4-all-deps.jar:?]
        at neurord.numeric.grid.AdaptiveGridCalc.init(AdaptiveGridCalc.java:47) ~[neurord-3.1.4-all-deps.jar:?]
        at neurord.numeric.grid.GridCalc._run(GridCalc.java:87) ~[neurord-3.1.4-all-deps.jar:?]
        at neurord.numeric.BaseCalc.run(BaseCalc.java:123) ~[neurord-3.1.4-all-deps.jar:?]
        at neurord.SDCalc.run(SDCalc.java:87) [neurord-3.1.4-all-deps.jar:?]
        at neurord.StochDiff.main(StochDiff.java:184) [neurord-3.1.4-all-deps.jar:?]